import { FirebaseError } from "firebase/app";
import { FIREBASE_ERROR_CODE } from "@/constants";
import { CHANGE_PASSWORD_ERROR_CODE } from "../constants";
import type { ChangePasswordError } from "../models";

export const mapChangePasswordError = (error: unknown): ChangePasswordError => {
  if (!(error instanceof FirebaseError)) {
    return { code: CHANGE_PASSWORD_ERROR_CODE.UNKNOWN };
  }

  const errorCodeMap: Readonly<Record<string, ChangePasswordError["code"]>> = {
    [FIREBASE_ERROR_CODE.INVALID_CREDENTIAL]:
      CHANGE_PASSWORD_ERROR_CODE.CURRENT_INVALID,
    [FIREBASE_ERROR_CODE.INVALID_USER_TOKEN]:
      CHANGE_PASSWORD_ERROR_CODE.REAUTHENTICATION_INVALID,
    [FIREBASE_ERROR_CODE.NETWORK_REQUEST_FAILED]:
      CHANGE_PASSWORD_ERROR_CODE.NETWORK,
    [FIREBASE_ERROR_CODE.REQUIRES_RECENT_LOGIN]:
      CHANGE_PASSWORD_ERROR_CODE.REAUTHENTICATION_INVALID,
    [FIREBASE_ERROR_CODE.TOO_MANY_REQUESTS]:
      CHANGE_PASSWORD_ERROR_CODE.TOO_MANY_ATTEMPTS,
    [FIREBASE_ERROR_CODE.USER_MISMATCH]:
      CHANGE_PASSWORD_ERROR_CODE.REAUTHENTICATION_INVALID,
    [FIREBASE_ERROR_CODE.USER_TOKEN_EXPIRED]:
      CHANGE_PASSWORD_ERROR_CODE.REAUTHENTICATION_INVALID,
    [FIREBASE_ERROR_CODE.WEAK_PASSWORD]:
      CHANGE_PASSWORD_ERROR_CODE.WEAK_PASSWORD,
    [FIREBASE_ERROR_CODE.WRONG_PASSWORD]:
      CHANGE_PASSWORD_ERROR_CODE.CURRENT_INVALID,
  };

  return {
    code: errorCodeMap[error.code] ?? CHANGE_PASSWORD_ERROR_CODE.UNKNOWN,
  };
};
